server:
  port: 8888    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7777/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com.example.eurekaclient: DEBUG
spring:
profile: container
  datasource:
    url: jdbc:mysql://mysql:3306/league_db?serverTimezone=Europe/Kiev&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
I:
  WANT:
      hhhhh
